//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.03.07 at 03:40:00 PM CET 
//


package gregl.energydataapi.model;

import jakarta.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the gregl.soap.data package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: gregl.soap.data
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetEnergyDataByYearAndMonthRequest }
     * 
     */
    public GetEnergyDataByYearAndMonthRequest createGetEnergyDataByYearAndMonthRequest() {
        return new GetEnergyDataByYearAndMonthRequest();
    }

    /**
     * Create an instance of {@link GetEnergyDataByYearAndMonthResponse }
     * 
     */
    public GetEnergyDataByYearAndMonthResponse createGetEnergyDataByYearAndMonthResponse() {
        return new GetEnergyDataByYearAndMonthResponse();
    }

    /**
     * Create an instance of {@link EnergyDataList }
     * 
     */
    public EnergyDataList createEnergyDataList() {
        return new EnergyDataList();
    }

    /**
     * Create an instance of {@link EnergyData }
     * 
     */
    public EnergyData createEnergyData() {
        return new EnergyData();
    }

}
