//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.03.07 at 03:40:00 PM CET 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://gregl/soap/data.wsdl", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package gregl.energydataapi.model;
